usernameElement='//android.widget.EditText[@content-desc="test-Username"]'
passwordElement='//android.widget.EditText[@content-desc="test-Password"]'
loginBtnElement='//android.view.ViewGroup[@content-desc="test-LOGIN"]'
username='standard_user'
password='secret_sauce'
burgerMenuElement='//android.view.ViewGroup[@content-desc="test-Menu"]/android.view.ViewGroup/android.widget.ImageView'
webViewMenuElement='//android.view.ViewGroup[@content-desc="test-WEBVIEW"]/android.widget.TextView'
closeMenuElement='//android.view.ViewGroup[@content-desc="test-Close"]/android.widget.ImageView'
AllItemElement='//android.view.ViewGroup[@content-desc="test-ALL ITEMS"]/android.widget.TextView'
webviewInputTextElement='//android.widget.EditText[@content-desc="test-enter a https url here..."]'
gotoSiteBtnElement='//android.view.ViewGroup[@content-desc="test-GO TO SITE"]'
toogleListItemElement='//android.view.ViewGroup[@content-desc="test-Toggle"]/android.widget.ImageView'
chartElement='//android.view.ViewGroup[@content-desc="test-Cart"]/android.view.ViewGroup/android.widget.ImageView'
checkoutBtnElement='//android.view.ViewGroup[@content-desc="test-CHECKOUT"]'
continueShoopingElement='//android.view.ViewGroup[@content-desc="test-CONTINUE SHOPPING"]'
deleteItemElement='//android.view.ViewGroup[@content-desc="test-Delete"]/android.view.ViewGroup'
viewItemElement='//android.view.ViewGroup[@content-desc="test-Item"][1]/android.view.ViewGroup/android.widget.ImageView'
viewItemLargeElement='//android.view.ViewGroup[@content-desc="test-Image Container"]/android.widget.ImageView'
backToProductFromDetailElement='//android.view.ViewGroup[@content-desc="test-BACK TO PRODUCTS"]'
addToCartElement='//android.view.ViewGroup[@content-desc="test-ADD TO CART"]'
removeBtnElement='//android.view.ViewGroup[@content-desc="test-REMOVE"][1]'
removeItemCartElement='(//android.view.ViewGroup[@content-desc="test-REMOVE"])[1]'
removeItemCartElement='//android.view.ViewGroup[@content-desc="test-Delete"]/android.view.ViewGroup'
firstNameCheckoutElement='//android.widget.EditText[@content-desc="test-First Name"]'
lastNameCheckoutElement='//android.widget.EditText[@content-desc="test-Last Name"]'
postalCodeCheckoutElement='//android.widget.EditText[@content-desc="test-Zip/Postal Code"]'
cancelCheckoutElement='//android.view.ViewGroup[@content-desc="test-CANCEL"]'
continueCheckoutElement='//android.view.ViewGroup[@content-desc="test-CONTINUE"]'
finishCheckoutElement='//android.view.ViewGroup[@content-desc="test-FINISH"]'
completeCheckout='THANK YOU FOR YOU ORDER'
backToHomeCheckoutElement='//android.view.ViewGroup[@content-desc="test-FINISH"]'

# SauceLabs RN
productsHeader='//android.view.ViewGroup[@content-desc="container header"]/android.widget.TextView'
sauceLabBackpack='//android.view.ViewGroup[@content-desc="store item"][1]/android.view.ViewGroup[1]/android.widget.ImageView'
sauceLabBikeLight='//android.view.ViewGroup[@content-desc="store item"][2]/android.view.ViewGroup[1]/android.widget.ImageView'
modalRating='//android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup'
closeModalRating='//android.view.ViewGroup[@content-desc="Close Modal button"]'
colorRed='//android.view.ViewGroup[@content-desc="red circle"]/android.view.ViewGroup'
counterPlus='//android.view.ViewGroup[@content-desc="counter plus button"]/android.widget.ImageView'
counterMinus='//android.view.ViewGroup[@content-desc="counter minus button"]/android.widget.ImageView'
addToCart='//android.view.ViewGroup[@content-desc="Add To Cart button"]'
iconCart='//android.view.ViewGroup[@content-desc="cart badge"]/android.widget.ImageView'
myCartHeader='//android.view.ViewGroup[@content-desc="container header"]/android.widget.TextView'
removeItem='//android.view.ViewGroup[@content-desc="remove item"]/android.widget.TextView'
proceedCheckout='//android.view.ViewGroup[@content-desc="Proceed To Checkout button"]'
loginHeader='//android.view.ViewGroup[@content-desc="container header"]/android.widget.TextView'
autoFillAccount='//android.view.ViewGroup[@content-desc="bob@example.com-autofill"]/android.widget.TextView'
loginBtn='//android.view.ViewGroup[@content-desc="Login button"]'
checkoutHeader='//android.view.ViewGroup[@content-desc="container header"]/android.widget.TextView'
fullNameField='//android.widget.EditText[@content-desc="Full Name* input field"]'
addressField='//android.widget.EditText[@content-desc="Address Line 1* input field"]'
cityField='//android.widget.EditText[@content-desc="City* input field"]'
stateField='//android.widget.EditText[@content-desc="State/Region input field"]'
zipCodeField='//android.widget.EditText[@content-desc="Zip Code* input field"]'
countryField='//android.widget.EditText[@content-desc="Country* input field"]'
btnToPayment='//android.view.ViewGroup[@content-desc="To Payment button"]'
enterPaymentHeader='//android.widget.ScrollView[@content-desc="checkout payment screen"]/android.view.ViewGroup/android.widget.TextView[1]'
cardNumberField='//android.widget.EditText[@content-desc="Card Number* input field"]'
expiredDateField='//android.widget.EditText[@content-desc="Expiration Date* input field"]'
securityCodeField='//android.widget.EditText[@content-desc="Security Code* input field"]'
checkboxField='//android.view.ViewGroup[@content-desc="checkbox for My billing address is the same as my shipping address."]/android.view.ViewGroup/android.widget.ImageView'
btnReviewOrder='//android.view.ViewGroup[@content-desc="Review Order button"]'
reviewOrderHeader='//android.widget.ScrollView[@content-desc="checkout review order screen"]/android.view.ViewGroup/android.widget.TextView'
btnPlaceOrder='//android.view.ViewGroup[@content-desc="Place Order button"]'
checkoutCompleteHeader='//android.view.ViewGroup[@content-desc="checkout complete screen"]/android.widget.ScrollView/android.view.ViewGroup/android.widget.TextView[1]'
btnContinueShopping='//android.view.ViewGroup[@content-desc="Continue Shopping button"]'

# Burger Menu
burgerMenu='//android.view.ViewGroup[@content-desc="open menu"]/android.widget.ImageView'