usernameElement='//android.widget.EditText[@content-desc="test-Username"]'
passwordElement='//android.widget.EditText[@content-desc="test-Password"]'
loginBtnElement='//android.view.ViewGroup[@content-desc="test-LOGIN"]'
username='standard_user'
password='secret_sauce'
burgerMenuElement='//android.view.ViewGroup[@content-desc="test-Menu"]/android.view.ViewGroup/android.widget.ImageView'
webViewMenuElement='//android.view.ViewGroup[@content-desc="test-WEBVIEW"]/android.widget.TextView'
closeMenuElement='//android.view.ViewGroup[@content-desc="test-Close"]/android.widget.ImageView'
AllItemElement='//android.view.ViewGroup[@content-desc="test-ALL ITEMS"]/android.widget.TextView'
webviewInputTextElement='//android.widget.EditText[@content-desc="test-enter a https url here..."]'
gotoSiteBtnElement='//android.view.ViewGroup[@content-desc="test-GO TO SITE"]'
toogleListItemElement='//android.view.ViewGroup[@content-desc="test-Toggle"]/android.widget.ImageView'
chartElement='//android.view.ViewGroup[@content-desc="test-Cart"]/android.view.ViewGroup/android.widget.ImageView'
checkoutBtnElement='//android.view.ViewGroup[@content-desc="test-CHECKOUT"]'
continueShoopingElement='//android.view.ViewGroup[@content-desc="test-CONTINUE SHOPPING"]'
viewItemElement='(//android.view.ViewGroup[@content-desc="test-Item"])[1]/android.view.ViewGroup/android.widget.ImageView'
viewItemLargeElement='//android.view.ViewGroup[@content-desc="test-Image Container"]/android.widget.ImageView'
backToProductFromDetailElement='//android.view.ViewGroup[@content-desc="test-BACK TO PRODUCTS"]'
addToCartElement='//android.view.ViewGroup[@content-desc="test-ADD TO CART"]'
removeBtnElement='(//android.view.ViewGroup[@content-desc="test-REMOVE"])[1]'
removeItemCartElement='(//android.view.ViewGroup[@content-desc="test-REMOVE"])[1]'
removeItemCartElement='//android.view.ViewGroup[@content-desc="test-Delete"]/android.view.ViewGroup'
firstNameCheckoutElement='//android.widget.EditText[@content-desc="test-First Name"]'
lastNameCheckoutElement='//android.widget.EditText[@content-desc="test-Last Name"]'
postalCodeCheckoutElement='//android.widget.EditText[@content-desc="test-Zip/Postal Code"]'
cancelCheckoutElement='//android.view.ViewGroup[@content-desc="test-CANCEL"]'
continueCheckoutElement='//android.view.ViewGroup[@content-desc="test-CONTINUE"]'
finishCheckoutElement='//android.view.ViewGroup[@content-desc="test-FINISH"]'
completeCheckout='THANK YOU FOR YOUR ORDER'
backToHomeCheckoutElement='//android.view.ViewGroup[@content-desc="test-FINISH"]'
